spring:
  application:
    name: ishop-api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

